name: Run Tests using CppUtest Framework

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CppUtest dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y -q --no-install-recommends file git gcc g++ make automake autoconf libtool
      - name: Clone and Build CppUtest
        run: |
          git config --global http.sslVerify false \
          git clone https://github.com/cpputest/cpputest.git \
          cd cpputest && autoreconf . -i && ./configure && make tdd -j$(nproc) && export CPPUTEST_HOME=$PWD && cd ..
      - name: Build and Run Unit Tests
        run: |
          make clean
          make tests
