name: Run Tests using CppUtest Framework

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mfbsouza/cpputest-docker
      options: --user root
    steps:
      - name: Disable git SSL verification
        run: |
          git config --global http.sslverify false
      - uses: actions/checkout@v3
      - name: Build and Run Unit Tests
        run: |
          make clean
          make tests
